---
name: PR-check-tox
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
jobs:
  Run PR tests:
    steps:

      - name: Import WF
        uses: reartnew/cjunct.github/workflows/main-check-tox.yml
