---
name: PR-check-tox
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
jobs:
  steps:

    - name: Checkout source
      uses: actions/checkout@v3

    - name: Import WF
      uses: .github/workflows/main-check-tox.yml
